### ISSUE TITLE
This shit doesnt let me play my games anymore

### ISSUE THREAD

**Issue by matheusnotfound** [AurieFramework/Aurie#13]
after using it i went play the games but it said it had no executable but it was right there i did EVERYTHING to fix it, nothing worked

**Comment by Archie-osu** [comment]
Your antivirus removed the AurieLoader.exe file. Known issue, nothing I can do about it. Reinstall Aurie using the Aurie Manager or any game specific tooling.

**Comment by Archie-osu** [comment]
Closing as fixed.
